# -------  Project Basic Config -------

mageops_project: app
mageops_environment: raccoon

mageops_app_is_magesuite: yes
mageops_magesuite_domain: "magesuite.me"

# Universal credentials used wherever possible
mageops_raccoon_app_id: "{{ mageops_project | lower | regex_replace('[^a-z0-9]+', '_') | truncate(10, true, '') }}"
mageops_raccoon_password: racc00n

# -------  Magento Infrastructure Config  -------

# Do not set a fixed base URL allowing access from any host
magento_base_url: ~
magento_bounce_email_address: raccoon@mageops.sh

# -------  Magento Installation Config  -------

magento_currency: EUR
magento_language: en_US

# -------  Magento Core Config  -------

# Disable redirect to base so shop can be accessed by IP / without domain
magento_core_config_enable_redirect_to_base: 0

# Remove base-urls for the aboe purpose
magento_core_config_settings_to_remove_extra:
  - web/unsecure/base_url
  - web/secure/base_url

# -------  Magento Admin Config  -------

magento_admin_path: admin
magento_admin_user_username: admin
magento_admin_user_email: admin@magesuite.me
magento_admin_user_firstname: Creativecoon
magento_admin_user_lastname: Stylera

# -------  Magento / Import -------

# Whether to enable the custom MageSuite import dispatcher service
magento_import_dispatcher_enable: no

# -------  Magento / SCD  -------

magento_scd_strategy: quick
magento_scd_parallel_jobs: 1

# No need to waste time compiling Luma when you use custom themes
magento_scd_excluded_themes:
  - "Magento/luma"

magento_scd_languages:
  - "en_US"
  - "de_DE"

# -------  Optional services  -------

# Whether install RabbitMQ and configure Magento to use it
# > Note: New Magento version automatically fall-back to database
# > queue implementations if RabbitMQ is not configured.
magento_rabbitmq_queue: no
